// Shared products list for the site
window.products = [
  { name: "HormoBalance Talbeena", badge: "Best Seller", icon: "./images/Product3.png", price: "PKR 899", desc: "250g | Dietitian-formulated functional blend specially designed to support hormonal balance in women, particularly those managing PCOS. Combines traditional barley nutrition with seed cycling blend for natural hormone support and healthy weight management." },
  { name: "Golden Age Talbeena", badge: "Premium", icon: "./images/Product2.png", price: "PKR 799", desc: "250g | Luxurious, dietitian-crafted wellness blend inspired by traditional Sunnah nutrition. Ideal for complete nourishment, strength, and balanced health. Supports digestive health, heart vitality, mental calmness, and is suitable for all age groups, especially seniors." },
  { name: "Luteal Phase Seed Mix", badge: "Featured", icon: "./images/Product8.jpeg", price: "PKR 899", desc: "200g | Sunflower Seeds + Sesame Seeds. Designed for your luteal phase (Day 15–28) with a nourishing blend to balance progesterone, reduce PMS symptoms, and promote calm, steady energy. Rich in selenium for liver detox, magnesium for mood support, and Vitamin E for glowing skin." },
  { name: "Follicular Phase Seed Mix", badge: "Popular", icon: "./images/Product7.jpeg", price: "PKR 749", desc: "200g | Pumpkin Seeds + Flaxseeds. Support your body naturally during the follicular phase (Day 1–14) with a powerful blend rich in lignans and zinc. Helps balance estrogen levels, supports PCOS & cycle health, boosts energy & metabolism." },
  { name: "Almonds (Badam)", badge: "Natural", icon: "./images/Product1.jpeg", price: "PKR 449 - 1,120", desc: "Premium quality King of Nuts. 100g = PKR 449 | 250g = PKR 1,120. Boosts brain function and memory, improves skin glow and hair strength, supports heart health. Rich in Vitamin E and healthy fats for maintaining energy levels." },
  { name: "Foxnuts (Makhana)", badge: "Wellness", icon: "./images/Product4.jpeg", price: "PKR 400 - 749", desc: "Low-calorie superfood. 50g = PKR 400 | 100g = PKR 749. High in antioxidants, supports weight loss and fat control. Helps regulate blood sugar levels, supports heart and thyroid health. Perfect for healthy snacking and detox diets." },
];
